import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.io.*;
import javax.imageio.*;
/**
 * Canvas is used to draw all predefined store components given to it.
 * The canvas does not calculate the location of components other than relative to each other in special cases, only draws then outputs to screen.
 * 
 * @author Greg Myers
 * @version 2011,03,18
 */
public class Canvas extends JPanel 
{
    private final int WIDTH = 1280;
    private final int HEIGHT = 720;
    private JPanel p;
    private JFrame f;
    private Image canvasImage;
    private Graphics g;
    private final int CUSTOMER_DIAMETER = 16;
    /**
     * Checkout width used in controller to decide how large to draw some components.
     */
    public final int CHECKOUT_WIDTH = 20;
    /**
     * Checkout length used in controller to decide how large to draw some components.
     */
    public final int CHECKOUT_LENGTH = 160;
    /**
     * Constructor for objects of class Canvas.
     * Creates a frame with a content pant of a panel and ovverides that panel to draw an image generated by the abstract graphics class.
     */
    public Canvas()
    {
        f = new JFrame(); //creates a frame
        p = new JPanel()
        {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(canvasImage, 0, 0, null);//g.drawLine(0,0,100,100);
            } //overrides paintComponent to draw automatically
        }; //creates a panel
        p.setPreferredSize(new Dimension(WIDTH,HEIGHT));
        p.setDoubleBuffered(true);
        f.setContentPane(p); //adds panel to frame
        f.pack(); //resizes frame
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //Sets close behaviour
        f.setVisible(true); //paint
        //
        canvasImage = p.createImage(WIDTH,HEIGHT); //makes off screen drawing place
        g = (Graphics)canvasImage.getGraphics(); //
        //g.setColor(new Color(255,0,0)); //sets next color
        //g.fillRect(0, 0, WIDTH/2,HEIGHT/2); //makes a full screen rectangle with color
    }

    private void addCheckout(int index, int Y)
    {
        //g.setColor(new Color(221,77,0));
        //g.fillRect(index*CHECKOUT_WIDTH,Y,CHECKOUT_WIDTH-1,CHECKOUT_LENGTH);
        try{
            File sourceimage = new File("checkout.png");
            Image image = ImageIO.read(sourceimage);
            int x = CHECKOUT_LENGTH/image.getHeight(this);
            for (int y = 0; y < x; y++)
            {
                g.drawImage(image,index*CHECKOUT_WIDTH,(Y+y*image.getHeight(this)),CHECKOUT_WIDTH-1,image.getHeight(this), this);
            }
        } catch (IOException e) {
        }

        //g.setColor(new Color(255,0,0));
        //int[] x = {(index*CHECKOUT_WIDTH),(index*CHECKOUT_WIDTH)+(CHECKOUT_WIDTH/2),(index*CHECKOUT_WIDTH)+(CHECKOUT_WIDTH)};
        //int[] y = {Y+25+CHECKOUT_LENGTH,Y+CHECKOUT_LENGTH,Y+25+CHECKOUT_LENGTH};
        //g.fillPolygon(new Polygon(x,y,3));
        try{
            File sourceimage = new File("till.png");
            Image image = ImageIO.read(sourceimage);
            g.drawImage(image,(index*CHECKOUT_WIDTH),(Y+CHECKOUT_LENGTH),(CHECKOUT_WIDTH),(CHECKOUT_WIDTH)/2, this);
        } catch (IOException e) {
        }
        //p.repaint();
    }

    private void addCustomer(Point coords)
    {
        try{
            File sourceimage = new File("customer.png");
            Image image = ImageIO.read(sourceimage);
            g.drawImage(image,(int)coords.getX(),(int)coords.getY(),CUSTOMER_DIAMETER,CUSTOMER_DIAMETER, this);
        } catch (IOException e) {
        }
        //g.setColor(new Color(0,0,255));
        //g.fillOval((int)coords.getX(),(int)coords.getY(),CUSTOMER_DIAMETER,CUSTOMER_DIAMETER);
    }

    private void addCustomer(int column, int row, int shopHeight)
    {
        //g.setColor(new Color(0,0,255));
        //g.fillOval(row*CHECKOUT_WIDTH,((shopHeight + CHECKOUT_LENGTH - 20 )-column*CHECKOUT_WIDTH), CUSTOMER_DIAMETER,CUSTOMER_DIAMETER);
        try{
            File sourceimage = new File("customer.png");
            Image image = ImageIO.read(sourceimage);
            g.drawImage(image, row*CHECKOUT_WIDTH,((shopHeight + CHECKOUT_LENGTH - 20 )-column*CHECKOUT_WIDTH),CUSTOMER_DIAMETER,CUSTOMER_DIAMETER, this);
        } catch (IOException e) {
        }
    }

    /**
     * adds a shop floor area, calls methods to add all other elements.
     * @param size the size of the shop floor.
     * @param aisles the location of impassable aisles on the shop floor.
     * @param checkoutArea the size of the checkout area.
     * @param checkouts contains the customers in the queues.
     * @param customers contains the coordinates of the customers on the shop floor.
     */
    public void addShopFloor(Dimension size, ArrayList<Point> aisles, Dimension checkoutArea, ArrayList<Integer> checkouts, ArrayList<Point> customers)
    {
        p.setPreferredSize(new Dimension((int)size.getWidth(),(int)(size.getHeight()+CHECKOUT_LENGTH+75)));

        //g.setColor(new Color(255,255,255));
        //g.fillRect(0,0,(int)size.getWidth(),(int)size.getHeight());        //
        try{
            File sourceimage = new File("floor.png");
            Image image = ImageIO.read(sourceimage);
            int x = (int)size.getWidth()/image.getWidth(this);
            int y = (int)size.getHeight()/image.getHeight(this);
            for (int i = 0; i < x; i++)
            {
                for (int j = 0; j < y; j++)
                {
                    g.drawImage(image,i*image.getWidth(this),j*image.getHeight(this),image.getWidth(this),image.getHeight(this), this);
                }
            }
            //g.drawImage(image, 0,0,(int)size.getWidth(),(int)size.getHeight(), this);
        } catch (IOException e) {
        }

        //g.setColor(new Color(100,100,100));
        for (Point aisle:aisles){
            //g.fillRect((int)aisle.getX(),(int)aisle.getY(),(int)size.getWidth()-40,20);
            try{
                File sourceimage = new File("aisles.png");
                Image image = ImageIO.read(sourceimage);
                int x = ((int)size.getWidth()-(40+image.getWidth(this)))/image.getWidth(this);
                for (int i=0; i<x; i++)
                {
                    g.drawImage(image,(i*image.getWidth(this))+(int)aisle.getX(),(int)aisle.getY(),image.getWidth(this),20, this);
                }
            } catch (IOException e) {
            }
        }
        //addCheckoutArea(checkoutArea, (int)size.getHeight());
        for (int i = 0; i<checkouts.size();i++){
            addCheckout(i,(int)size.getHeight());
            for (int j = 0; j<checkouts.get(i);j++){
                addCustomer(j,i,(int)size.getHeight());
            }
        }
        for (Point customer:customers){
            addCustomer(customer);
        }
        p.repaint();
    }

    /**
     * Draws the checkout area at the bottom of the shop area.
     * @param X The position of the top of the checkout area.
     */
    //private void addCheckoutArea(Dimension checkoutArea, int Y)
    //{
    //    g.setColor(new Color(88,11,0));
    //    g.fillRect(0,Y,(int)checkoutArea.getWidth(),(int)checkoutArea.getHeight()+Y);
    //}

    /**
     * Fills the default image size with black. Will not respond to resizing the window. Will take effect on the next panel repaint to minimize flickering.
     */
    public void erase()
    {
        g.setColor(new Color(0,0,0));
        g.fillRect(0,0,WIDTH,HEIGHT);
        //p.repaint();
    }
}
